<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { ElMessage } from 'element-plus'; import { api, errorMessage } from '../api/client'
const stats=ref<any>({}),users=ref<any[]>([]),courses=ref<any[]>([]),loading=ref(true)
async function load(){loading.value=true;try{const [{data:s},{data:u},{data:c}]=await Promise.all([api.get('/dashboard/admin'),api.get('/admin/users'),api.get('/courses')]);stats.value=s.data;users.value=u.data.items;courses.value=c.data.items}catch(e){ElMessage.error(errorMessage(e))}finally{loading.value=false}}
async function updateUser(user:any,status:string){try{const {data}=await api.patch(`/admin/users/${user.id}`,{status,is_active:status==='active'});Object.assign(user,data.data);ElMessage.success('用户状态已更新')}catch(e){ElMessage.error(errorMessage(e))}}
onMounted(load)
</script>
<template><div class="page" v-loading="loading"><div class="page-heading"><div><div class="eyebrow">ADMIN CONSOLE</div><h1>管理控制台</h1><p>查看系统运行状态、用户审核和课程知识库概况。</p></div><el-button @click="load">刷新数据</el-button></div><div class="stat-grid"><div class="surface stat-card"><div class="stat-label">注册用户</div><div class="stat-value">{{stats.users||0}}</div></div><div class="surface stat-card"><div class="stat-label">课程数量</div><div class="stat-value">{{stats.courses||0}}</div></div><div class="surface stat-card"><div class="stat-label">知识文档</div><div class="stat-value">{{stats.documents||0}}</div></div><div class="surface stat-card"><div class="stat-label">问答消息</div><div class="stat-value">{{stats.messages||0}}</div></div></div><div class="admin-grid"><section><div class="section-title"><h2>用户与审核</h2><el-tag v-if="stats.pending_users" type="warning">{{stats.pending_users}} 待审核</el-tag></div><div class="surface"><div v-for="user in users" :key="user.id" class="document-row" style="grid-template-columns:1fr .5fr auto"><div><strong>{{user.display_name}}</strong><div class="muted" style="font-size:12px">{{user.email}}</div></div><el-tag>{{user.role==='admin'?'管理员':'学生'}}</el-tag><el-dropdown @command="(s:string)=>updateUser(user,s)"><el-button size="small">{{user.status}}</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="active">通过审核</el-dropdown-item><el-dropdown-item command="pending">设为待审核</el-dropdown-item><el-dropdown-item command="rejected">拒绝/停用</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div></div></section><section><div class="section-title"><h2>课程概况</h2><span class="muted">{{courses.length}} 门</span></div><div class="surface"><div v-for="course in courses" :key="course.id" class="document-row" style="grid-template-columns:1fr auto"><div><strong>{{course.title}}</strong><div class="muted" style="font-size:12px">{{course.code}}</div></div><div class="muted" style="font-size:12px">{{course.document_count}} 资料 · {{course.member_count}} 成员</div></div></div></section></div><div class="section-title"><h2>最近管理记录</h2><span class="muted">失败文档 {{stats.failed_documents||0}} 份 · 回答反馈 {{stats.feedback||0}} 条</span></div><div class="surface"><div v-for="log in stats.recent_audit_logs" :key="log.id" class="document-row" style="grid-template-columns:1fr .8fr auto"><strong>{{log.action}}</strong><span class="muted">{{log.target_type}} · {{log.target_id||'-'}}</span><span class="muted" style="font-size:12px">{{new Date(log.created_at).toLocaleString()}}</span></div><div v-if="!stats.recent_audit_logs?.length" class="empty">暂无管理操作</div></div></div></template>

