<script setup lang="ts">
import { computed, nextTick, onMounted, reactive, ref } from 'vue'; import { useRoute } from 'vue-router'; import { ElMessage, ElMessageBox } from 'element-plus'; import { api, errorMessage } from '../api/client'; import { useAuthStore } from '../stores/auth'
const route=useRoute(),auth=useAuthStore(),courseId=computed(()=>String(route.params.id)),course=ref<any>({}),tab=ref('documents'),docs=ref<any[]>([]),members=ref<any[]>([]),memberEmail=ref(''),conversations=ref<any[]>([]),activeConversation=ref<any>(null),messages=ref<any[]>([]),citations=ref<any[]>([]),question=ref(''),asking=ref(false),summaries=ref<any[]>([]),quizzes=ref<any[]>([]),activeQuiz=ref<any>(null),answers=ref<number[]>([]),quizResult=ref<any>(null),uploading=ref(false),summaryLoading=ref(false)
const canManage=computed(()=>auth.isAdmin)
async function loadBase(){try{const [{data:c},{data:d},{data:m},{data:v},{data:s},{data:q}]=await Promise.all([api.get(`/courses/${courseId.value}`),api.get(`/courses/${courseId.value}/documents`),api.get(`/courses/${courseId.value}/members`),api.get('/conversations',{params:{course_id:courseId.value}}),api.get(`/courses/${courseId.value}/summaries`),api.get(`/courses/${courseId.value}/quizzes`)]);course.value=c.data;docs.value=d.data;members.value=m.data;conversations.value=v.data;summaries.value=s.data;quizzes.value=q.data}catch(e){ElMessage.error(errorMessage(e))}}
async function addMember(){if(!memberEmail.value.trim())return;try{await api.post(`/courses/${courseId.value}/members`,{email:memberEmail.value.trim()});memberEmail.value='';await loadBase();ElMessage.success('成员添加成功')}catch(e){ElMessage.error(errorMessage(e))}}
async function removeMember(member:any){await ElMessageBox.confirm(`确认移除 ${member.user.display_name}？`,'成员管理',{type:'warning'});try{await api.delete(`/courses/${courseId.value}/members/${member.id}`);members.value=members.value.filter(item=>item.id!==member.id);ElMessage.success('成员已移除')}catch(e){ElMessage.error(errorMessage(e))}}
async function checksum(file:File){const bytes=await file.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,'0')).join('')}
async function upload(file:any){uploading.value=true;try{const raw=file.raw as File;const mime=raw.type||'application/octet-stream';const {data:specResponse}=await api.post('/documents/upload-url',{course_id:courseId.value,filename:raw.name,mime_type:mime,size_bytes:raw.size});const spec=specResponse.data;let document;if(spec.mode==='presigned'){const uploaded=await fetch(spec.url,{method:'PUT',headers:spec.headers,body:raw});if(!uploaded.ok)throw new Error('对象存储上传失败');const {data}=await api.post(`/courses/${courseId.value}/documents`,{original_name:raw.name,storage_key:spec.storage_key,mime_type:mime,size_bytes:raw.size,checksum:await checksum(raw)});document=data.data}else{const fd=new FormData();fd.append('course_id',courseId.value);fd.append('file',raw);const {data}=await api.post('/documents/upload-local',fd);document=data.data}docs.value.unshift(document);ElMessage.success('上传成功，正在构建知识库');await processDoc(document.id)}catch(e){ElMessage.error(errorMessage(e))}finally{uploading.value=false}return false}
async function processDoc(id:string){try{const {data}=await api.post(`/documents/${id}/process`);const index=docs.value.findIndex(d=>d.id===id);if(index>=0)docs.value[index]=data.data;ElMessage.success('文档处理完成')}catch(e){ElMessage.error(errorMessage(e));await loadBase()}}
async function deleteDoc(doc:any){await ElMessageBox.confirm(`确认删除《${doc.original_name}》？`,'删除资料',{type:'warning'});try{await api.delete(`/documents/${doc.id}`);docs.value=docs.value.filter(d=>d.id!==doc.id);ElMessage.success('已删除')}catch(e){ElMessage.error(errorMessage(e))}}
async function newConversation(){const {data}=await api.post('/conversations',{course_id:courseId.value});activeConversation.value=data.data;conversations.value.unshift(data.data);messages.value=[];citations.value=[];tab.value='chat'}
async function openConversation(conv:any){activeConversation.value=conv;const {data}=await api.get(`/conversations/${conv.id}/messages`);messages.value=data.data;citations.value=[...(messages.value.filter(m=>m.role==='assistant').at(-1)?.citations||[])]}
async function send(){if(!question.value.trim()||asking.value)return;if(!activeConversation.value)await newConversation();const content=question.value.trim();messages.value.push({id:'temp-user',role:'user',content,citations:[]});const assistant=reactive({id:'temp-ai',role:'assistant',content:'',citations:[]});messages.value.push(assistant);question.value='';asking.value=true;citations.value=[];await nextTick();try{const token=localStorage.getItem('access_token');const response=await fetch(`${api.defaults.baseURL}/conversations/${activeConversation.value.id}/messages`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({content})});if(!response.ok)throw new Error('问答请求失败');const reader=response.body!.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop()||'';for(const event of events){const lines=event.split('\n'),type=lines.find(l=>l.startsWith('event:'))?.slice(6).trim(),raw=lines.find(l=>l.startsWith('data:'))?.slice(5).trim();if(!raw)continue;const data=JSON.parse(raw);if(type==='token')assistant.content+=data.text;if(type==='citations'){citations.value=data;assistant.citations=data}if(type==='done'){assistant.id=data.message.id;assistant.content=data.message.content}if(type==='error')throw new Error(data.message)}}await loadConversations()}catch(e){assistant.content='回答生成失败，请稍后重试。';ElMessage.error(errorMessage(e))}finally{asking.value=false}}
async function loadConversations(){const {data}=await api.get('/conversations',{params:{course_id:courseId.value}});conversations.value=data.data}
async function favorite(message:any){try{const {data}=await api.post(`/messages/${message.id}/favorite`);ElMessage.success(data.message)}catch(e){ElMessage.error(errorMessage(e))}}
async function feedback(message:any,rating:number){try{await api.post(`/messages/${message.id}/feedback`,{rating,comment:''});ElMessage.success('感谢反馈')}catch(e){ElMessage.error(errorMessage(e))}}
async function generateSummary(){summaryLoading.value=true;try{const {data}=await api.post(`/courses/${courseId.value}/summary`);summaries.value.unshift(data.data);ElMessage.success('课程摘要已生成')}catch(e){ElMessage.error(errorMessage(e))}finally{summaryLoading.value=false}}
async function generateQuiz(count=5){try{const {data}=await api.post(`/courses/${courseId.value}/quizzes`,{count});quizzes.value.unshift(data.data);await openQuiz(data.data.id);ElMessage.success('智能测验已生成')}catch(e){ElMessage.error(errorMessage(e))}}
async function openQuiz(id:string){const {data}=await api.get(`/quizzes/${id}`);activeQuiz.value=data.data;answers.value=new Array(data.data.question_count).fill(-1);quizResult.value=null}
async function submitQuiz(){if(answers.value.some(v=>v<0)){ElMessage.warning('请完成全部题目');return}try{const {data}=await api.post(`/quizzes/${activeQuiz.value.id}/submit`,{answers:answers.value});quizResult.value=data.data;activeQuiz.value=data.data.quiz;ElMessage.success(`提交成功，得分 ${data.data.score}`)}catch(e){ElMessage.error(errorMessage(e))}}
onMounted(async()=>{await loadBase();if(conversations.value.length)await openConversation(conversations.value[0])})
</script>
<template><div class="page"><div class="page-heading"><div><span class="course-code">{{course.code}}</span><h1 style="margin-top:12px">{{course.title}}</h1><p>{{course.description}}</p></div><el-button type="primary" @click="newConversation">发起新对话</el-button></div>
<el-tabs v-model="tab" class="surface" style="padding:0 22px 22px">
<el-tab-pane label="课程资料" name="documents"><div v-if="canManage" class="upload-zone"><el-upload :auto-upload="false" :show-file-list="false" accept=".docx,.pdf,.txt,.md" :on-change="upload"><el-button type="primary" :loading="uploading">上传课程资料</el-button></el-upload><div class="muted" style="font-size:12px;margin-top:10px">支持 DOCX、PDF、TXT、Markdown，单文件不超过 25 MB</div></div><div class="surface" style="box-shadow:none"><div v-for="doc in docs" :key="doc.id" class="document-row"><div><strong>{{doc.original_name}}</strong><div class="muted" style="font-size:12px;margin-top:5px">{{(doc.size_bytes/1024/1024).toFixed(2)}} MB · {{doc.chunk_count}} 个知识片段</div></div><div class="hide-mobile"><el-tag :type="doc.status==='ready'?'success':doc.status==='failed'?'danger':'warning'">{{doc.status==='ready'?'可检索':doc.status==='processing'?'处理中':doc.status==='failed'?'失败':'待处理'}}</el-tag></div><div class="hide-mobile muted" style="font-size:12px">{{doc.error_message||'状态正常'}}</div><div v-if="canManage"><el-button v-if="doc.status!=='ready'" link type="primary" @click="processDoc(doc.id)">处理</el-button><el-button link type="danger" @click="deleteDoc(doc)">删除</el-button></div></div><div v-if="!docs.length" class="empty">知识库暂无资料</div></div></el-tab-pane>
<el-tab-pane label="AI 问答" name="chat"><div class="workspace"><aside class="conversation-list"><el-button type="primary" plain style="width:100%;margin-bottom:12px" @click="newConversation">＋ 新对话</el-button><div v-for="conv in conversations" :key="conv.id" class="conversation-item" :class="{active:activeConversation?.id===conv.id}" @click="openConversation(conv)">{{conv.title}}</div></aside><section class="chat-column"><div class="messages"><div v-if="!messages.length" class="empty"><h3 style="color:#172033">向课程资料提问</h3><p>例如：RAG 为什么能减少大模型幻觉？</p></div><div v-for="message in messages" :key="message.id" class="message" :class="message.role"><div class="avatar">{{message.role==='user'?'我':'AI'}}</div><div><div class="bubble">{{message.content||'正在思考…'}}</div><div v-if="message.role==='assistant'&&message.id!=='temp-ai'" class="message-actions"><span @click="favorite(message)" style="cursor:pointer">☆ 收藏</span><span @click="feedback(message,1)" style="cursor:pointer">👍 有帮助</span><span @click="feedback(message,-1)" style="cursor:pointer">👎 需改进</span></div></div></div></div><div class="composer"><el-input v-model="question" type="textarea" :autosize="{minRows:1,maxRows:4}" placeholder="只依据当前课程资料回答…" @keydown.enter.exact.prevent="send"/><el-button type="primary" :loading="asking" @click="send">发送</el-button></div></section><aside class="citation-panel"><strong>回答依据</strong><p class="muted" style="font-size:12px">点击引用可核对课程原文片段</p><div v-for="c in citations" :key="c.chunk_id" class="citation-card"><strong>[{{c.source_id}}] {{c.document_name}}</strong><p>{{c.excerpt}}</p><div class="muted" style="font-size:11px;margin-top:8px">相关度 {{Math.round(c.score*100)}}%<span v-if="c.page_number"> · 第 {{c.page_number}} 页</span></div></div><div v-if="!citations.length" class="empty" style="padding:40px 0">暂无引用</div></aside></div></el-tab-pane>
<el-tab-pane label="课程摘要" name="summary"><div style="text-align:right;margin-bottom:16px"><el-button type="primary" :loading="summaryLoading" @click="generateSummary">生成课程摘要</el-button></div><div v-for="s in summaries" :key="s.id" class="summary-grid" style="margin-bottom:20px"><section class="surface content-card" style="box-shadow:none"><h3>课程概述</h3><p style="line-height:1.9">{{s.overview}}</p><h3>核心知识点</h3><ul class="point-list"><li v-for="p in s.key_points" :key="p">{{p}}</li></ul></section><aside class="surface content-card" style="box-shadow:none"><h3>关键词</h3><span v-for="k in s.keywords" :key="k" class="keyword">{{k}}</span><h3 style="margin-top:24px">复习建议</h3><ul class="point-list"><li v-for="p in s.review_suggestions" :key="p">{{p}}</li></ul></aside></div><div v-if="!summaries.length" class="empty">生成摘要后，可快速掌握课程重点。</div></el-tab-pane>
<el-tab-pane label="智能测验" name="quiz"><div style="display:flex;justify-content:space-between;margin-bottom:16px"><el-select v-if="quizzes.length" placeholder="选择历史测验" @change="openQuiz"><el-option v-for="q in quizzes" :key="q.id" :label="q.title" :value="q.id"/></el-select><el-button type="primary" @click="generateQuiz(5)">生成 5 道题</el-button></div><div v-if="activeQuiz"><el-alert v-if="quizResult" :title="`测验得分：${quizResult.score} 分（答对 ${quizResult.correct_count}/${quizResult.total}）`" type="success" show-icon :closable="false" style="margin-bottom:18px"/><article v-for="(q,i) in activeQuiz.questions" :key="q.id" class="surface quiz-question"><h3>{{Number(i)+1}}. {{q.stem}}</h3><el-radio-group v-model="answers[Number(i)]" class="quiz-options" :disabled="!!quizResult"><el-radio v-for="(option,j) in q.options" :key="j" :value="Number(j)" border>{{String.fromCharCode(65+Number(j))}}. {{option}}</el-radio></el-radio-group><el-alert v-if="quizResult" :title="q.explanation" :type="answers[Number(i)]===q.correct_index?'success':'error'" :closable="false" style="margin-top:16px"/><div v-if="quizResult" class="citation-card"><strong>来源：{{q.citation.document_name}}</strong><p>{{q.citation.excerpt}}</p></div></article><el-button v-if="!quizResult" type="primary" size="large" @click="submitQuiz">提交测验</el-button></div><div v-else class="empty">生成一套基于课程资料的智能测验。</div></el-tab-pane>
<el-tab-pane v-if="canManage" label="成员管理" name="members"><div style="display:flex;gap:12px;margin-bottom:20px"><el-input v-model="memberEmail" placeholder="输入已注册用户邮箱" @keyup.enter="addMember"/><el-button type="primary" @click="addMember">添加成员</el-button></div><div class="surface" style="box-shadow:none"><div v-for="member in members" :key="member.id" class="document-row" style="grid-template-columns:1fr .5fr auto"><div><strong>{{member.user.display_name}}</strong><div class="muted" style="font-size:12px">{{member.user.email}}</div></div><el-tag>{{member.member_role==='owner'?'课程负责人':'课程成员'}}</el-tag><el-button v-if="member.member_role!=='owner'" link type="danger" @click="removeMember(member)">移除</el-button></div></div></el-tab-pane>
<el-tab-pane label="学习记录" name="history"><div class="surface" style="box-shadow:none"><div v-for="conv in conversations" :key="conv.id" class="document-row" @click="tab='chat';openConversation(conv)" style="cursor:pointer"><div><strong>{{conv.title}}</strong><div class="muted" style="font-size:12px;margin-top:5px">{{new Date(conv.updated_at).toLocaleString()}}</div></div><el-button link type="primary">继续对话</el-button></div><div v-if="!conversations.length" class="empty">暂无学习记录</div></div></el-tab-pane>
</el-tabs></div></template>
