<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { ElMessage } from 'element-plus'; import { api, errorMessage } from '../api/client'; import { useAuthStore } from '../stores/auth'
const auth=useAuthStore(),router=useRouter(),courses=ref<any[]>([]),loading=ref(true),showJoin=ref(false),showCreate=ref(false)
const stats=reactive({course_count:0,conversation_count:0,favorite_count:0,quiz_average:0}),joinCode=ref(''),courseForm=reactive({code:'',title:'',description:''})
async function load(){loading.value=true;try{await auth.fetchMe();const [{data:c},{data:s}]=await Promise.all([api.get('/courses'),api.get('/dashboard/student')]);courses.value=c.data.items;Object.assign(stats,s.data)}catch(e){ElMessage.error(errorMessage(e))}finally{loading.value=false}}
async function join(){try{await api.post('/courses/join',{code:joinCode.value});ElMessage.success('已加入课程');showJoin.value=false;await load()}catch(e){ElMessage.error(errorMessage(e))}}
async function create(){try{await api.post('/courses',courseForm);ElMessage.success('课程创建成功');showCreate.value=false;await load()}catch(e){ElMessage.error(errorMessage(e))}}
onMounted(load)
</script>
<template><div class="page"><div class="page-heading"><div><div class="eyebrow">LEARNING OVERVIEW</div><h1>你好，{{auth.user?.display_name}}</h1><p>从课程资料中找到答案，建立可验证的知识体系。</p></div><div><el-button @click="showJoin=true">加入课程</el-button><el-button v-if="auth.isAdmin" type="primary" @click="showCreate=true">创建课程</el-button></div></div>
<div class="stat-grid"><div class="surface stat-card"><div class="stat-label">我的课程</div><div class="stat-value">{{stats.course_count}}</div></div><div class="surface stat-card"><div class="stat-label">学习对话</div><div class="stat-value">{{stats.conversation_count}}</div></div><div class="surface stat-card"><div class="stat-label">收藏回答</div><div class="stat-value">{{stats.favorite_count}}</div></div><div class="surface stat-card"><div class="stat-label">测验平均分</div><div class="stat-value">{{stats.quiz_average}}<small style="font-size:14px;color:#98a2b3"> / 100</small></div></div></div>
<div class="section-title"><h2>我的课程</h2><span class="muted">{{courses.length}} 门课程</span></div><div v-loading="loading" class="course-grid"><article v-for="course in courses" :key="course.id" class="surface course-card" @click="router.push(`/courses/${course.id}`)"><span class="course-code">{{course.code}}</span><h3>{{course.title}}</h3><p class="muted" style="font-size:14px;line-height:1.6;min-height:44px">{{course.description||'暂无课程简介'}}</p><div class="course-meta"><span>{{course.document_count}} 份资料</span><span>{{course.member_count}} 位成员</span></div></article></div><div v-if="!loading&&!courses.length" class="surface empty">暂无课程，输入课程代码加入学习空间。</div>
<el-dialog v-model="showJoin" title="加入课程" width="420"><el-input v-model="joinCode" placeholder="请输入课程代码，如 AI-FOUNDATION" /><template #footer><el-button @click="showJoin=false">取消</el-button><el-button type="primary" @click="join">加入</el-button></template></el-dialog>
<el-dialog v-model="showCreate" title="创建课程" width="480"><el-form label-position="top"><el-form-item label="课程代码"><el-input v-model="courseForm.code" /></el-form-item><el-form-item label="课程名称"><el-input v-model="courseForm.title" /></el-form-item><el-form-item label="课程简介"><el-input v-model="courseForm.description" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="showCreate=false">取消</el-button><el-button type="primary" @click="create">创建</el-button></template></el-dialog>
</div></template>

